### PR TITLE
Fix a few straggling \rm -> \mathrm{..} in LaTeX

### LINKED ISSUE #3037: \rm deprecated in LaTeX
Since \rm is deprecated in LaTeX (it has been for 28 years), we should replace it overtime with \mathrm{...} (since symbol definitions assume we are in math mode) or at least use the latter for new symbols. Currently, set.mm has 828 occurrences of `\rm`.

(Remark: also deprecated in LaTeX are: \rm, \it, \bf, \tt, \sc, \sl, \sf and also `$$ ... $$` for displayed equations.)

### PR DESCRIPTION
**Pull request by david-a-wheeler**
fixes #3037

### CODE REVIEW

File: set.mm [hunk 1]
```diff
@@ -437504,10 +437504,10 @@ orthogonal vectors (i.e. whose inner product is 0) is the sum of the
 /* Elementary  geometry (extension)  */
 htmldef "LineM" as 'LineM';
  althtmldef "LineM" as 'Line<sub>M</sub>';
- latexdef "LineM" as "{\rm Line}_M";
+ latexdef "LineM" as "{\mathrm{Line}_M}";
```
Comment (tirix) [inline set.mm:437507]: The outside brackets can be removed here, I guess.

**Review by tirix — APPROVED** [review]

File: set.mm (hunk 1 above)
Comment (benjub) [reply set.mm:437507]: By the way: anyone knows why the "suggestion" feature is unavailable ? It would be pretty handy here: we could even apply the suggestion and merge without waiting.

Comment (david-a-wheeler) [reply set.mm:437507]: @benjub - you have write access to this repo, so you *should* be able to the suggestion feature as far as I know.

Comment (benjub) [reply set.mm:437507]:
```suggestion
 latexdef "LineM" as "\mathrm{Line}_M";
```

Comment (benjub) [reply set.mm:437507]: Just made the suggestion after several different trials (the button was inactive when in "Review" mode for a reason I cannot pin down).

File: iset.mm [hunk 2]
```diff
@@ -129928,27 +129928,27 @@ Norman Megill (2007) section 1.1.3.  Megill then states, "A number of
   althtmldef "-1-1->" as
     '&ndash;<FONT SIZE=-2 FACE=sans-serif>1-1</FONT>&rarr;';
   latexdef "-1-1->" as
-    "\raisebox{.5ex}{${\textstyle{\:}_{\mbox{\footnotesize\rm 1" +
-    "\tt -\rm 1}}}\atop{\textstyle{" +
-    "\longrightarrow}\atop{\textstyle{}^{\mbox{\footnotesize\rm {\ }}}}}$}";
+    "\raisebox{.5ex}{${\textstyle{\:}_{\mbox{\footnotesize\mathrm{1}" +
+    "\tt -\mathrm{1}}}}\atop{\textstyle{" +
+    "\longrightarrow}\atop{\textstyle{}^{\mbox{\footnotesize\mathrm{\ }}}}}$}";
```
Comment (benjub) [inline iset.mm:129933]: > \mathrm{\ }

not sure about that but this overly complicated latexdef will hopefully soon go away, see #3054

**Review by benjub — APPROVED** [review]

File: set.mm (hunk 1 above)
Comment (benjub) [inline set.mm:437507]:
```suggestion
 latexdef "LineM" as "\mathrm{Line}_M";
```

Comment (benjub) [reply set.mm:437507]: I cannot apply the suggestion... "This diff has recently been updated. Refresh and try again." but refreshing has no effect...

**Comment by benjub** [comment]
@david-a-wheeler can you apply the suggestion so that we can merge ?

File: set.mm (hunk 1 above)
Comment (tirix) [reply set.mm:437507]: I can see the button "commit suggestion". I tried several times but each time I get "_This diff has recently been updated - Refresh and try again_"

Comment (david-a-wheeler) [reply set.mm:437507]: Okay, will do!

File: iset.mm (hunk 2 above)
Comment (david-a-wheeler) [reply iset.mm:129933]: Well, `\mathrm{\ }`  does have an effect - it creates horizontal space like a Roman-style space. If we don't need it, let's remove it, but I presumed it was put in for a reason. Let's make removing that a separate proposal (as discussed).

**Comment by david-a-wheeler** [comment]
Changed per discussion above, and it has 2 approvers. Presuming it passes the verifiers, I plan to merge it very soon.
